spring:
  application:
    name: "configserver"
  profiles:
    #active: native  #classpath
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations: "classpath:/config"
          #search-locations: "file:///Users//nirmit//Documents//config"
       git:
#         uri: "https://github.com/eazybytes/eazybytes-config.git"
         uri: "https://github.com/NirmitJain/eazybytes-config.git"
         username: 'nirmitjain'
         password: 'GitPass@@80'
         default-label: main #branch name in git
         timeout: 10 # in seconds
         clone-on-start: true # clone the gothub repo in local startup
         force-pull: true
management:
  endpoints:
    web:
      expose:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      applications: ${spring.application.name}
encrypt:
  key: "4133823363D8F87BFECFACDDB6338"

server:
  port: 8071

logging:
  pattern:
    level: "%5p [${spring.application.name}, %X{trace_id}, %X{span_id}]"


